"""empty message

Revision ID: 36767a86b96a
Revises: 92f4a7e53a78
Create Date: 2022-09-03 18:05:06.297045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36767a86b96a'
down_revision = '92f4a7e53a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_username')
    # ### end Alembic commands ###
