"""empty message

Revision ID: 49f0d4f5c7be
Revises: 7ba3cd281ee1
Create Date: 2022-08-31 20:25:45.719130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f0d4f5c7be'
down_revision = '7ba3cd281ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feedback', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'feedback')
    # ### end Alembic commands ###
