"""empty message

Revision ID: 6fb13ae587ae
Revises: 49f0d4f5c7be
Create Date: 2022-08-31 20:43:10.307538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fb13ae587ae'
down_revision = '49f0d4f5c7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feedback', mysql.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###
