"""empty message

Revision ID: 8ffa07517e4f
Revises: 36767a86b96a
Create Date: 2022-09-03 18:19:07.308421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ffa07517e4f'
down_revision = '36767a86b96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_name'])
    op.drop_column('users', 'user_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_username', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
