"""empty message

Revision ID: 92f4a7e53a78
Revises: 7a14a8cbef7d
Create Date: 2022-09-03 18:04:31.943142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92f4a7e53a78'
down_revision = '7a14a8cbef7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_feedback',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=120), nullable=False))
    op.drop_table('short_feedback')
    # ### end Alembic commands ###
