"""empty message

Revision ID: 9e9227bc9e72
Revises: 375e324e885f
Create Date: 2022-09-02 18:09:02.885159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9227bc9e72'
down_revision = '375e324e885f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_feedback',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_feedback')
    # ### end Alembic commands ###
