"""empty message

Revision ID: d3ce5b9cdb96
Revises: de4b07ef45c4
Create Date: 2022-09-03 18:37:09.651915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3ce5b9cdb96'
down_revision = 'de4b07ef45c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=120), nullable=False))
    op.drop_index('user_name', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('user_name', 'users', ['user_name'], unique=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
