"""empty message

Revision ID: de4b07ef45c4
Revises: d268a0abbe37
Create Date: 2022-09-03 18:26:45.530083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de4b07ef45c4'
down_revision = 'd268a0abbe37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['user_name'])
    op.drop_column('users', 'user_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_username', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
